### ISSUE TITLE
Add code/documentation for downloading images

### ISSUE THREAD

**Issue by kosmas10** [davidedelpapa/gphotospy#1]
Please provide documentation on how to download an image, and even better, create a function that can download an image from Google Photos to a specific local folder, preserving the original date of the image (i.e. the date of the file should be the original photo date), its full resolution (no cropping or resizing), and as much as possible of the original metadata (I think only the location is unavailable in Google photos).

**Comment by davidedelpapa** [comment]
I am currently working at it as part of the effort to map the result of the `list()` or `get()` method to a newly introduced `MediaItem` object (inherits from `Val`)

**Comment by davidedelpapa** [comment]
Added a new class `MediaItem` to map the results of `Media.list()` and `Media.get()`.

This class has got a `raw_download()` method that downloads the raw bytes of the media file.

Downloading now is as easy as 

```python
photo_iterator = media_manager.search(MEDIAFILTER.PHOTO)
media = MediaItem(next(photo_iterator))
with open(media.filename(), 'wb') as output:
    output.write(media.raw_download())
```
Documentation is also available as a [tutorial 02](https://github.com/davidedelpapa/gphotospy/wiki/tut_02) in the wiki
