### ISSUE TITLE
Token expired

### ISSUE THREAD

**Issue by Eserim** [davidedelpapa/gphotospy#27]
Hi - I had all this working fine and was just making final tweaks to a program that would, every month, re-populate a "Month In History" folder with a random selection of pictures from that month, for use in my Chromecast With Google TV screensaver, but then I got

    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})

I have recreated all the steps in the google Dev site for the token file, but without any luck

Thoughts?

Cheers

**Comment by Eserim** [comment]
deleting the token file on the running device seems to have sorted - it looks like in the test mode there are only 50 requests allowed per token

**Comment by davidedelpapa** [comment]
Thank you @Eserim to point that out
