### ISSUE TITLE
iterator returns a continuous loop

### ISSUE THREAD

**Issue by heckmaninnovations** [davidedelpapa/gphotospy#8]
The iterator that returns search results is neverending. It just keeps looping through the same set of files continuously.

**Comment by heckmaninnovations** [comment]
I see the issue.  The package on pypi doesn't have the fix that was created for this that sets the new page token inside the loop on the Media class search function.

**Comment by davidedelpapa** [comment]
Indeed. I updated the pypi package, now it is in sync with the current.

**Comment by davidedelpapa** [comment]
> I see the issue. The package on pypi doesn't have the fix that was created for this that sets the new page token inside the loop on the Media class search function.

thank you for the catch. I couldn't reproduce it :-)
